// @ts-nocheck — auto-generated, do not edit
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tenants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Tenants
         * @description 가입자 목록 (conversations 테이블에서 tenant 집계).
         */
        get: operations["list_tenants_api_tenants_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/judges": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Judges
         * @description 선택 가능한 Judge LLM 목록 (API 키 등록 여부 반영).
         */
        get: operations["list_judges_api_judges_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/t/{tenant}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Run
         * @description 평가 실행. (M3) mock 모드에서는 구성을 EvalRun으로 등록하고 요약 반환.
         */
        post: operations["create_run_api_t__tenant__runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/t/{tenant}/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Conversations
         * @description 가입자의 대화 세션 목록 (싱글턴/멀티턴).
         */
        get: operations["list_conversations_api_t__tenant__conversations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/t/{tenant}/evaluations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Explore Evaluations
         * @description tenant 평가 탐색 (필터).
         */
        get: operations["explore_evaluations_api_t__tenant__evaluations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/t/{tenant}/trends": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Tenant Trends
         * @description tenant 메트릭 추이 (group_by=day|run, 일자 범위 필터).
         */
        get: operations["tenant_trends_api_t__tenant__trends_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/t/{tenant}/agreement": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Tenant Agreement
         * @description 휴먼 vs 자동 일치도.
         */
        get: operations["tenant_agreement_api_t__tenant__agreement_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/t/{tenant}/agreement/{metric}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Tenant Agreement Samples
         * @description 특정 메트릭의 휴먼·자동 표본 상세 (드릴다운).
         */
        get: operations["tenant_agreement_samples_api_t__tenant__agreement__metric__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/t/{tenant}/kb": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Tenant Kb
         * @description tenant 지식베이스 현황 + 검색 커버리지 갭.
         */
        get: operations["tenant_kb_api_t__tenant__kb_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/t/{tenant}/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Settings
         * @description tenant 설정 조회.
         */
        get: operations["get_settings_api_t__tenant__settings_get"];
        /**
         * Put Settings
         * @description tenant 설정 저장.
         */
        put: operations["put_settings_api_t__tenant__settings_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/t/{tenant}/review-queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Review Queue
         * @description 검수 대기 평가 (저신뢰·미검수 우선순위).
         */
        get: operations["review_queue_api_t__tenant__review_queue_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evaluations/{eval_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Evaluation Single
         * @description 단일 평가 상세 (검수 워크스페이스용, run 무관).
         */
        get: operations["get_evaluation_single_api_evaluations__eval_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/review/{eval_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit Review
         * @description 휴먼 재평가 확정 — Final Score 갱신 + 골든셋 적재.
         */
        post: operations["submit_review_api_review__eval_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{conversation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Conversation
         * @description 세션 상세 — 대화 타임라인 + 턴/세션 평가.
         */
        get: operations["get_conversation_api_conversations__conversation_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_api_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Summary */
        get: operations["get_summary_api_runs__run_id__summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/evaluations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Evaluations */
        get: operations["get_evaluations_api_runs__run_id__evaluations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/evaluations/{eval_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Evaluation */
        get: operations["get_evaluation_api_runs__run_id__evaluations__eval_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/trends": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Trends
         * @description 전체 run의 메트릭 평균 추이 (회귀 감지용)
         */
        get: operations["get_trends_api_runs__run_id__trends_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AgreementResult
         * @description 휴먼 vs 자동 일치도
         */
        AgreementResult: {
            /**
             * Available
             * @default false
             */
            available: boolean;
            /**
             * Overall Agreement
             * @default 0
             */
            overall_agreement: number;
            /**
             * N
             * @default 0
             */
            n: number;
            /** Per Metric */
            per_metric?: {
                [key: string]: {
                    [key: string]: number;
                };
            };
        };
        /**
         * AgreementSample
         * @description 일치도 표본 상세 (메트릭 드릴다운)
         */
        AgreementSample: {
            /** Eval Id */
            eval_id: string;
            /** Conversation Id */
            conversation_id?: string | null;
            /**
             * Query
             * @default
             */
            query: string;
            /**
             * Review Status
             * @default
             */
            review_status: string;
            /** Reviewer */
            reviewer?: string | null;
            /**
             * Auto Score
             * @default 0
             */
            auto_score: number;
            /**
             * Human Score
             * @default 0
             */
            human_score: number;
            /**
             * Delta
             * @default 0
             */
            delta: number;
            /**
             * Agree
             * @default true
             */
            agree: boolean;
        };
        /** AuditSummaryResponse */
        AuditSummaryResponse: {
            /** Run Id */
            run_id: string;
            /** Generated At */
            generated_at?: string | null;
            /** Total Calls */
            total_calls: number;
            /** Total Evaluations */
            total_evaluations: number;
            /** Flagged Call Ids */
            flagged_call_ids?: string[];
            /** Metrics */
            metrics?: components["schemas"]["MetricSummary"][];
        };
        /**
         * ClaimVerdict
         * @description RAGAS 스타일 claim 단위 검증 결과
         */
        ClaimVerdict: {
            /** Claim */
            claim: string;
            /** Supported */
            supported: boolean;
            /** Verdict */
            verdict: string;
            /**
             * Reasoning
             * @default
             */
            reasoning: string;
        };
        /**
         * ConversationDetail
         * @description 세션 상세 — 대화 원문 + 턴/세션 평가
         */
        ConversationDetail: {
            /** Conversation Id */
            conversation_id: string;
            /**
             * Tenant Id
             * @default default
             */
            tenant_id: string;
            /** Subscriber Id */
            subscriber_id?: string | null;
            /**
             * Is Multiturn
             * @default false
             */
            is_multiturn: boolean;
            /** Started At */
            started_at?: string | null;
            /** Turns */
            turns?: components["schemas"]["ConversationTurnView"][];
            /** Turn Evaluations */
            turn_evaluations?: {
                [key: string]: unknown;
            }[];
            /** Session Evaluation */
            session_evaluation?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * ConversationInfo
         * @description 세션 목록 항목
         */
        ConversationInfo: {
            /** Conversation Id */
            conversation_id: string;
            /**
             * Tenant Id
             * @default default
             */
            tenant_id: string;
            /** Subscriber Id */
            subscriber_id?: string | null;
            /**
             * Is Multiturn
             * @default false
             */
            is_multiturn: boolean;
            /**
             * Turn Count
             * @default 0
             */
            turn_count: number;
            /**
             * Pending Review
             * @default 0
             */
            pending_review: number;
            /** Started At */
            started_at?: string | null;
            /** Session Scores */
            session_scores?: {
                [key: string]: number;
            };
        };
        /** ConversationTurnView */
        ConversationTurnView: {
            /** Role */
            role: string;
            /** Content */
            content: string;
        };
        /** EvaluationResponse */
        EvaluationResponse: {
            /** Eval Id */
            eval_id: string;
            /** Qa Id */
            qa_id?: string | null;
            /** Call Id */
            call_id: string;
            /**
             * Tenant Id
             * @default default
             */
            tenant_id: string;
            /** Conversation Id */
            conversation_id?: string | null;
            /** Subscriber Id */
            subscriber_id?: string | null;
            /**
             * Level
             * @default turn
             */
            level: string;
            /** Turn Index */
            turn_index?: number | null;
            /** Query */
            query: string;
            /** Generated Answer */
            generated_answer: string;
            /**
             * Judge Provider
             * @default openai
             */
            judge_provider: string;
            /**
             * Judge Model
             * @default gpt-4o
             */
            judge_model: string;
            /** Evaluated At */
            evaluated_at?: string | null;
            retrieval_result?: components["schemas"]["RetrievalResultResponse"] | null;
            /** Scores */
            scores?: components["schemas"]["MetricScoreResponse"][];
            /**
             * Review Status
             * @default pending
             */
            review_status: string;
            /** Human Scores */
            human_scores?: {
                [key: string]: number;
            };
            /** Human Label */
            human_label?: string[];
            /**
             * Human Comment
             * @default
             */
            human_comment: string;
            /** Reviewer */
            reviewer?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
        };
        /**
         * JudgeModel
         * @description 선택 가능한 Judge LLM
         */
        JudgeModel: {
            /** Provider */
            provider: string;
            /** Model */
            model: string;
            /** Label */
            label: string;
            /**
             * Available
             * @default true
             */
            available: boolean;
            /**
             * Note
             * @default
             */
            note: string;
        };
        /**
         * KbGap
         * @description 검색 커버리지 갭 — 검색 품질이 낮았던 질의
         */
        KbGap: {
            /** Query */
            query: string;
            /** Conversation Id */
            conversation_id?: string | null;
            /**
             * Context Recall
             * @default 0
             */
            context_recall: number;
        };
        /**
         * KbStatus
         * @description tenant 지식베이스 현황
         */
        KbStatus: {
            /** Tenant Id */
            tenant_id: string;
            /**
             * Document Count
             * @default 0
             */
            document_count: number;
            /**
             * Chunk Count
             * @default 0
             */
            chunk_count: number;
            /** Source Types */
            source_types?: string[];
            /** Last Indexed At */
            last_indexed_at?: string | null;
            /**
             * Avg Context Recall
             * @default 0
             */
            avg_context_recall: number;
            /** Coverage Gaps */
            coverage_gaps?: components["schemas"]["KbGap"][];
        };
        /** MetricScoreResponse */
        MetricScoreResponse: {
            /** Metric */
            metric: string;
            /** Score */
            score: number;
            /**
             * Reasoning
             * @default
             */
            reasoning: string;
            /** Grounding Chunks */
            grounding_chunks?: string[];
            /**
             * Confidence
             * @default 1
             */
            confidence: number;
            /** Sample Scores */
            sample_scores?: number[];
            /**
             * Is Low Confidence
             * @default false
             */
            is_low_confidence: boolean;
            /** Claims */
            claims?: components["schemas"]["ClaimVerdict"][];
            /** Human Score */
            human_score?: number | null;
            /** Final Score */
            final_score?: number | null;
        };
        /** MetricSummary */
        MetricSummary: {
            /** Metric */
            metric: string;
            /** Mean */
            mean: number;
            /** Median */
            median: number;
            /** P10 */
            p10: number;
            /** P90 */
            p90: number;
            /** Below Sla Count */
            below_sla_count: number;
            /** Total Count */
            total_count: number;
            /** Sla Pass Rate */
            sla_pass_rate: number;
        };
        /** RetrievalResultResponse */
        RetrievalResultResponse: {
            /** Query */
            query: string;
            /** Hyde Query */
            hyde_query?: string | null;
            /** Sub Queries */
            sub_queries?: string[];
            /** Contexts */
            contexts?: components["schemas"]["RetrievedContextResponse"][];
        };
        /** RetrievedContextResponse */
        RetrievedContextResponse: {
            /** Chunk Id */
            chunk_id: string;
            /** Content */
            content: string;
            /** Score */
            score: number;
            /** Bm25 Score */
            bm25_score?: number | null;
            /** Dense Score */
            dense_score?: number | null;
            /**
             * Source Call Id
             * @default
             */
            source_call_id: string;
        };
        /** ReviewResult */
        ReviewResult: {
            /** Eval Id */
            eval_id: string;
            /** Ok */
            ok: boolean;
            /** Review Status */
            review_status: string;
        };
        /**
         * ReviewSubmit
         * @description 휴먼 재평가 확정 (POST 본문)
         */
        ReviewSubmit: {
            /** Status */
            status: string;
            /** Human Scores */
            human_scores?: {
                [key: string]: number;
            };
            /** Labels */
            labels?: string[];
            /**
             * Comment
             * @default
             */
            comment: string;
            /** Reviewer */
            reviewer?: string | null;
        };
        /**
         * RunEvalConfig
         * @description 평가 실행 구성 (POST 본문)
         */
        RunEvalConfig: {
            /** Judges */
            judges?: string[];
            /**
             * Ensemble
             * @default false
             */
            ensemble: boolean;
            /** Levels */
            levels?: string[];
            /** Metrics */
            metrics?: string[];
            /** Methods */
            methods?: string[];
            /**
             * Target
             * @default all
             */
            target: string;
            /**
             * Temperature
             * @default 0
             */
            temperature: number;
        };
        /**
         * RunEvalResult
         * @description 평가 실행 결과 요약
         */
        RunEvalResult: {
            /** Run Id */
            run_id: string;
            /** Tenant Id */
            tenant_id: string;
            /** Status */
            status: string;
            /** Judges */
            judges?: string[];
            /** Levels */
            levels?: string[];
            /** Methods */
            methods?: string[];
            /**
             * Total Evaluations
             * @default 0
             */
            total_evaluations: number;
            /**
             * Message
             * @default
             */
            message: string;
        };
        /** RunInfo */
        RunInfo: {
            /** Run Id */
            run_id: string;
            /** Generated At */
            generated_at?: string | null;
            /**
             * Total Calls
             * @default 0
             */
            total_calls: number;
            /**
             * Total Evaluations
             * @default 0
             */
            total_evaluations: number;
            /**
             * Flagged Count
             * @default 0
             */
            flagged_count: number;
            /**
             * Has Summary
             * @default true
             */
            has_summary: boolean;
        };
        /** TenantInfo */
        TenantInfo: {
            /** Tenant Id */
            tenant_id: string;
            /** Name */
            name: string;
            /**
             * Conversation Count
             * @default 0
             */
            conversation_count: number;
            /**
             * Pending Review Count
             * @default 0
             */
            pending_review_count: number;
        };
        /**
         * TenantSettings
         * @description tenant 설정 — SLA 임계값·옵션 프로필·Judge·알림
         */
        TenantSettings: {
            /** Tenant Id */
            tenant_id: string;
            /** Sla Thresholds */
            sla_thresholds?: {
                [key: string]: number;
            };
            /**
             * Eval Profile
             * @default 기본
             */
            eval_profile: string;
            /**
             * Default Judge
             * @default anthropic
             */
            default_judge: string;
            /** Judge Credentials */
            judge_credentials?: {
                [key: string]: boolean;
            };
            /**
             * Slack Webhook
             * @default
             */
            slack_webhook: string;
            /**
             * Notify On Regression
             * @default true
             */
            notify_on_regression: boolean;
            /** Reviewers */
            reviewers?: string[];
        };
        /** TrendPoint */
        TrendPoint: {
            /** Run Id */
            run_id?: string | null;
            /** Day */
            day?: string | null;
            /** Label */
            label?: string | null;
            /** Generated At */
            generated_at?: string | null;
            /** N */
            n?: number | null;
        } & {
            [key: string]: unknown;
        };
        /** TrendsResponse */
        TrendsResponse: {
            /** Points */
            points?: components["schemas"]["TrendPoint"][];
            /** Metrics */
            metrics?: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_tenants_api_tenants_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantInfo"][];
                };
            };
        };
    };
    list_judges_api_judges_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JudgeModel"][];
                };
            };
        };
    };
    create_run_api_t__tenant__runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunEvalConfig"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunEvalResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_conversations_api_t__tenant__conversations_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationInfo"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    explore_evaluations_api_t__tenant__evaluations_get: {
        parameters: {
            query?: {
                level?: string | null;
                metric?: string | null;
                review_status?: string | null;
                low_confidence_only?: boolean;
                below_metric?: string | null;
                below_threshold?: number | null;
            };
            header?: never;
            path: {
                tenant: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tenant_trends_api_t__tenant__trends_get: {
        parameters: {
            query?: {
                group_by?: string;
                date_from?: string | null;
                date_to?: string | null;
            };
            header?: never;
            path: {
                tenant: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrendsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tenant_agreement_api_t__tenant__agreement_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgreementResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tenant_agreement_samples_api_t__tenant__agreement__metric__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant: string;
                metric: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgreementSample"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tenant_kb_api_t__tenant__kb_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KbStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_settings_api_t__tenant__settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantSettings"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_settings_api_t__tenant__settings_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TenantSettings"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantSettings"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_queue_api_t__tenant__review_queue_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_evaluation_single_api_evaluations__eval_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eval_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_review_api_review__eval_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eval_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewSubmit"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_conversation_api_conversations__conversation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_api_runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunInfo"][];
                };
            };
        };
    };
    get_summary_api_runs__run_id__summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditSummaryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_evaluations_api_runs__run_id__evaluations_get: {
        parameters: {
            query?: {
                call_id?: string | null;
                subscriber_id?: string | null;
                flagged_only?: boolean;
                low_confidence_only?: boolean;
                below_metric?: string | null;
                below_threshold?: number | null;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_evaluation_api_runs__run_id__evaluations__eval_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
                eval_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_trends_api_runs__run_id__trends_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrendsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
